---
authors:
  - Sean Sullivan @sean-m-sullivan
  - Tom Page @Tompage1994
  - David Danielsson @djdanielsson
dependencies: {}
description: Ansible content that interacts with the Ansible Automation Hub or Galaxy NG API.
documentation: https://github.com/ansible/galaxy_collection/blob/devel/README.md
license:
  - GPL-3.0-only
namespace: galaxy
name: galaxy
version: 1.1.1-devel
readme: README.md
repository: https://github.com/ansible/galaxy_collection
issues: https://github.com/ansible/galaxy_collection/issues
tags:
  - cloud
  - infrastructure
  - galaxy
  - ansible
  - galaxy
  - automation
build_ignore:
  - tools
  - setup.cfg
  - galaxy.yml.j2
  - template_galaxy.yml
  - '*.tar.gz'
...
