---
- name: Testing Galaxy
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - galaxy.galaxy
  pre_tasks:
    - name: Include vars from ah_configs directory
      ansible.builtin.include_vars:
        dir: ./ah_configs
        extensions: ["yml"]
      tags:
        - always

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "{{ ah_configuration_working_dir }}"
        state: directory
        mode: '0755'

  tasks:
    - name: Authenticate and get an API token
      galaxy.galaxy.ah_token:
        ah_host: "{{ ah_hostname }}"
        ah_username: "{{ ah_username }}"
        ah_password: "{{ ah_password }}"
        ah_path_prefix: "{{ ah_path_prefix }}"
        validate_certs: "{{ ah_validate_certs }}"

    - name: Create ansible config file
      ansible.builtin.include_role:
        name: ansible_config

    - name: Create namespace
      ansible.builtin.include_role:
        name: namespace

    #  - name: Publish Collections
    #    ansible.builtin.include_role:
    #      name: publish
    #    vars:
    #      ah_auto_approve: true

    - name: Remove collection
      galaxy.galaxy.ah_collection:
        namespace: community_test
        name: test
        version: 1.0.1
        state: absent
        ah_host: "{{ ah_hostname }}"
        ah_token: "{{ ah_token }}"
        ah_path_prefix: "{{ ah_path_prefix }}"
        validate_certs: "{{ ah_validate_certs }}"

    - name: Add EE Registry
      galaxy.galaxy.ah_ee_registry:
        name: myreg
        url: https://registry.redhat.io
        ah_host: "{{ ah_hostname }}"
        ah_username: "{{ ah_username }}"
        ah_password: "{{ ah_password }}"
        ah_path_prefix: "{{ ah_path_prefix }}"
        validate_certs: "{{ ah_validate_certs }}"

    - name: Deauthenticate
      galaxy.galaxy.ah_token:
        ah_host: "{{ ah_hostname }}"
        ah_token: "{{ ah_token }}"
        ah_path_prefix: "{{ ah_path_prefix }}"
        validate_certs: "{{ ah_validate_certs }}"
        state: absent

...
