---
name: OCI Env Integration
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  integration:
    strategy:
      fail-fast: false
      matrix:
        env:
          - TEST_PROFILE: standalone
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout galaxy_ng
        uses: actions/checkout@v4
        with:
          repository: ansible/galaxy_ng
          path: galaxy_ng
          ref: master

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: test
        run: tree galaxy_ng

      # Note: COMPOSE_INTERACTIVE_NO_CLI=1 is required for oci-env to work correctly when there's no interactive terminal
      - name: Set environment variables
        run: |
          echo "OCI_ENV_PATH=${HOME}/work/galaxy_ng/oci_env" >> $GITHUB_ENV
          echo "GALAXY_ENV_PATH=${HOME}/work/" >> $GITHUB_ENV
          echo "COMPOSE_INTERACTIVE_NO_CLI=1" >> $GITHUB_ENV
          echo "OCI_VERBOSE=1" >> $GITHUB_ENV
          echo "GH_DUMP_LOGS=1" >> $GITHUB_ENV

      - name: Update apt
        run: sudo apt -y update

      - name: Install LDAP requirements
        run: sudo apt-get install -y libsasl2-dev python3 libldap2-dev libssl-dev build-essential

      - name: setup oci-env
        run: |
          git clone https://github.com/ansible/galaxy_ng.git /home/runner/work/galaxy_ng
          git clone https://github.com/pulp/oci_env.git /home/runner/work/galaxy_ng/oci_env/
          pip install -e $OCI_ENV_PATH/client/
          mkdir $OCI_ENV_PATH/db_backup/

      - name: run integration tests
        run: make gh-action/${{ matrix.env.TEST_PROFILE }}
        working-directory: /home/runner/work/galaxy_ng/

      - name: "Perform collection repository tests"
        run: ansible-playbook tests/playbooks/testing_collections_repos.yml -v -e galaxy_ng_version=${{ inputs.galaxy_ng_version }}
