---
name: Test roles and modules with galaxy_ng

on:
  workflow_call:
    inputs:
      galaxy_ng_version:
        description: The version to pull of galaxy_ng
        required: true
        type: string
      gh_ref:
        description: The ref in the repository to pull
        required: false
        default: devel
        type: string
    secrets:
      redhat_catalog_username:
        description: Username for Red Hat Catalog
        required: true
      redhat_catalog_password:
        description: Password for Red Hat Catalog
        required: true

jobs:

  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout galaxy_ng
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: install ansible
        run: pip3 install ansible

      - name: Checkout the galaxy collection
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.gh_ref }}
          repository: ansible/galaxy_collection
          path: galaxy_collection

      - name: Build and install the collection
        working-directory: galaxy_collection
        run: |
          # The ansible.cfg defined in the collection repository might break the test. We want the same variables for installation and running.
          rm -f ansible.cfg
          rm -f galaxy.yml
          mv .github/files/galaxy.yml.j2 .
          ansible all -i localhost, -c local -m template -a "src=galaxy.yml.j2 dest=galaxy.yml" -e collection_namespace=galaxy -e collection_name=galaxy -e collection_version=1.0.0 -e collection_repo=https://github.com/ansible/automation_hub_collection
          ansible-galaxy collection build -vvv
          ansible-galaxy collection install galaxy-galaxy-1.0.0.tar.gz -vvv

      - name: Spin up a standalone galaxy_ng installation
        run: |
          echo "COMPOSE_PROFILE=standalone" > .compose.env
          echo "DEV_SOURCE_PATH=galaxy_ng" >> .compose.env
          make docker/all
          ./compose up -d
          pip3 install --upgrade requests pyyaml
          python3 dev/common/poll.py

      - name: give stack some time to spin up
        run: sleep 240

      - name: Move ansible.cfg to root
        run: mv .github/files/ansible.cfg .

      - name: "Perform playbook collection tests"
        run: ansible-playbook tests/playbooks/testing_collections_playbook.yml -v -e galaxy_ng_version=${{ inputs.galaxy_ng_version }} -e git_repo_name=${{ github.event.repository.name }}
        if: |
          inputs.galaxy_ng_version == 'stable-4.4' ||
          inputs.galaxy_ng_version == 'stable-4.5' ||
          inputs.galaxy_ng_version == 'stable-4.6' ||
          inputs.galaxy_ng_version == 'stable-4.7'

      - name: "Perform collection repository tests"
        run: ansible-playbook tests/playbooks/testing_collections_repos.yml -v -e galaxy_ng_version=${{ inputs.galaxy_ng_version }}

      - name: "Perform playbook namespace tests"
        run: ansible-playbook tests/playbooks/testing_playbook_ee_namespace.yml -v -e galaxy_ng_version=${{ inputs.galaxy_ng_version }}
        if: ${{ inputs.galaxy_ng_version == 'stable-4.4' || inputs.galaxy_ng_version == 'stable-4.5'  }}  # ee_namespace APIs were removed in 4.6 (see #183)

      - name: "Perform playbook repository tests"
        run: ansible-playbook tests/playbooks/testing_playbook_ee_repository.yml -vv -e galaxy_ng_version=${{ inputs.galaxy_ng_version }} -e redhat_catalog_username=${{ secrets.redhat_catalog_username }} -e redhat_catalog_password=${{ secrets.redhat_catalog_password }}

      - name: "Perform playbook user and group management tests"
        run: ansible-playbook tests/playbooks/testing_playbook_user.yml -v -e galaxy_ng_version=${{ inputs.galaxy_ng_version }}
